root = "~/mail"
spool = "inbox"
sent = "sent-local"
drafts = "draft"
trash = "trash"
editor = "vim"
sendmail = "python3 -m norless.sendmail"
identities = ["Anton Bobrov <baverman@gmail.com>"]

auto_view = ["text/html", "text/calendar", "application/ics"]
alternative_order = ["text/plain", "text/html"]

[signatures]
"user@example.com" = "~/.signature"

[[mime]]
type = "text/html"
display = "w3m -dump -T text/html"
open = "xdg-open {file}"
